# See https://redoc.ly/docs/cli/configuration/ for more information.
apis:
  main:
    root: openapi/openapi.yaml
    x-openapi-ts:
      output: sdk/src/schema.d.ts
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
